demo/core/urls.py
from django.conf.urls import patterns, include, url

from core import views

urlpatterns = patterns('',
    url(r'^$', views.grid_view, name='grid'),
    url(r'^1/$', views.chart_one_view, name='1'),
    url(r'^2/$', views.chart_two_view, name='2'),
    url(r'^3/$', views.chart_three_view, name='3'),
    url(r'^4/$', views.chart_four_view, name='4'),
)

demo/core/forms.py
from django import forms
from django.utils.dates import MONTHS

class Filter(forms.Form):
    month = forms.ChoiceField(
        choices=MONTHS.items(),
        widget=forms.widgets.Select(
            attrs={'class':"form-control",
                   'placeholder':'Month'})
    )

demo/templates/front/base.html
{% extends 'front/layout.html' %}
{% block content %}
<div class="col-md-8">
<figure style="height: 400px;" id="myChart"></figure>
</div>
<div id="extra-chart" class="col-md-2">
{{ view.filter_form_html }}
</div>

{% endblock %}

demo/templates/front/layout.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link href="{{ STATIC_URL }}css/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/xcharts.css" rel="stylesheet">
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-2.0.0.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/d3.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/xcharts.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap/bootstrap.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            var data = JSON.parse('{{ view.chart_json_data | safe }}');
            var myChart = new xChart('bar', data, '#myChart', {
            {% comment %}
                sortX: function (a, b) {
                    console.log(a.y, b.y);
                    console.log((!a.y && !b.y) ? 0 : (a.y < b.y) ? -1 : 1);
                    return (!a.y && !b.y) ? 0 : (a.y < b.y) ? -1 : 1; }
            {% endcomment %}
            });

            $('#menu-link').find('a:not(#grid)').click(function(){
                $('#menu-link').find('li').each(function(){
                    $(this).removeClass('active');
                })
                $(this).parent('li').addClass('active');
                $.post($(this).attr('href'),
                        {'test':123},
                        function(json){
                            myChart.setData(json.chart_data);
                        $('#extra-chart').html(json.filter_form);
                        $('#id_month').change(function() {

                            $.post(
                                    $('#menu-link').find('li.active > a').attr('href'),
                                    {'filter': $(this).val()},
                                    function(json){
                                        myChart.setData(json.chart_data);
                                    }, 'json');

                            });
                }, 'json');
                return false;

            });
        });
    </script>
</head>
<body>
<div class="container">
    <div class="page-header">
      <h1>Example page header <small>Subtext for header</small></h1>
    </div>
    <div class="row">
      <div class="col-md-2">
            <ul id="menu-link" class="nav nav-pills nav-stacked">
              <li class="active">
                <a id="grid" href="{% url 'grid' %}">
                  grid
                </a>
              </li>
              <li>
                <a href="{% url '1' %}">
                  1 chart
                </a>
              </li>
              <li>
                <a href="{% url '2' %}">
                  2 chart
                </a>
              </li>
              <li>
                <a href="{% url '3' %}">
                  3 chart
                </a>
              </li>
              <li>
                <a href="{% url '4' %}">
                  4 chart
                </a>
              </li>
            </ul>
      </div>
      <div class="col-md-10">
        <div class="row">
          {% block content %}

          {% endblock %}
      </div>
      </div>
    </div>
</div>

</body>
</html>

demo/templates/front/table.html
{% extends 'front/layout.html' %}
{% block content %}
<div class="col-md-12">
    <table class="table">
        <thead>
        <tr>
          <th>Type</th>
          <th>Server</th>
          <th>Key</th>
          <th>Date</th>
          <th>Summary</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in view.objects %}
        <tr>
          <td>{{ obj.type }}</td>
          <td>{{ obj.server }}</td>
          <td>{{ obj.key }}</td>
          <td>{{ obj.date }}</td>
          <td>{{ obj.summary }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}